export { default as DriversLicenseSvg } from './DriversLicenseSvg'
export { default as NationalIdSvg } from './NationalIdSvg'
export { default as PassportSvg } from './PassportSvg'
export { default as ViewAllSvg } from './ViewAllSvg'
export { default as TickSvg } from './tick'
export { default as CircularTick } from './circular-tick'
